### ISSUE TITLE
Huge response truncates body

### ISSUE THREAD

**Issue by ofriedrich** [gmponos/guzzle-log-middleware#24]
If a response is larger than 3499 characters, the logger truncates the log to 200 characters, but does not rewind the stream! So the first 200 characters are missing later when the response is received!

File: src/Handler/MultiRecordArrayHandler.php
Line: 152

        if ($stream->getSize() >= 3500) {
            return $stream->read(200) . ' (truncated...)';
        }

=> missing `$stream->rewind()`

Found in gmponos/guzzle_logger v1.0.0

**Comment by gmponos** [comment]
Thanks for reporting the issue.
I pushed a new [commit](https://github.com/gmponos/guzzle-log-middleware/commit/5f2c7de051e02ce4141cbf9a5d436b53f1614787) and tagged a bug version. Can you check if this fixes your issue?

**Comment by ofriedrich** [comment]
Yes. Issue has been fixed.

Maybe you can think about the truncate itself. If a response is 3499 characters => whole response is logged. If a response has more than 3499 characters => only 200 chars are logged. Why not logging exactly 3500 chars? Best solution might be to make the limit configurable

**Comment by ofriedrich** [comment]
Any updates?

**Comment by gmponos** [comment]
> only 200 chars are logged

Well since I will truncate the body I want to have a short summary and not a 3500 characters. Most of the time in this cases it's a scrambled response of HTML or something like that.

>  Best solution might be to make the limit configurable

I created a new PR wanna have look #25

**Comment by gmponos** [comment]
I believe this to be fixed now.. if you want to have a look. Let me know if you need something :)
