### ISSUE TITLE
How we access MessageFormatter?

### ISSUE THREAD

**Issue by rognales** [gmponos/guzzle-log-middleware#33]
I want to customize the message.

If by hand, i normally do this.
````php
Middleware::log(
app(LogManager::class)->channel('api-log'),
new MessageFormatter($messageFormat)
 )
````

**Comment by gmponos** [comment]
Can you elaborate? The code you wrote is I think from creating a logger from guzzle https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L186

and the current package is not related with that code.

**Comment by rognales** [comment]
If i were to defined the structure of the message, i just need to create custom handler? Similar to ````MultiRecordArrayHandler```` ?

**Comment by gmponos** [comment]
There is this part in the readme file 

https://github.com/gmponos/guzzle-log-middleware#handlers

not sure what more can I add.. contributions are welcome.
