### ISSUE TITLE
Add support for PHP 8

### ISSUE THREAD

**Issue by allexyy** [gmponos/guzzle-log-middleware#39]
When using PHP 8.0.3 image in Dockerfile, composer install command returns error gmponos / guzzle_logger requires php (^ 7.2). Please add support for PHP 8

` Step 16/29 : RUN set -eux;     composer check-platform-reqs;     composer install --ignore-platform-reqs --no-dev --prefer-dist --no-dev --no-scripts --no-progress --no-suggest;     composer clear-cache
 ---> Running in 4406700576f0
+ composer check-platform-reqs
No vendor dir present, checking platform requirements from the lock file
composer-plugin-api  2.0.0                                                success  
ext-ctype            8.0.3                                                success  
ext-dom              20031129                                             success  
ext-filter           8.0.3                                                success  
ext-intl             8.0.3                                                success  
ext-json             8.0.3                                                success  
ext-libxml           8.0.3                                                success  
ext-mbstring         8.0.3                                                success  
ext-openssl          8.0.3                                                success  
ext-pcre             8.0.3                                                success  
ext-pdo              8.0.3                                                success  
ext-pdo_mysql        8.0.3                                                success  
ext-phar             8.0.3                                                success  
ext-simplexml        8.0.3                                                success  
ext-tokenizer        8.0.3                                                success  
ext-xml              8.0.3                                                success  
ext-xmlwriter        8.0.3                                                success  
php                  8.0.3     gmponos/guzzle_logger requires php (^7.2)  failed   
ERROR: Service 'php' failed to build: The command '/bin/sh -c set -eux;     composer check-platform-reqs;     composer install --ignore-platform-reqs --no-dev --prefer-dist --no-dev --no-scripts --no-progress --no-suggest;     composer clear-cache' returned a non-zero code: 1 `

PHP_VERSION=8.0.3-fpm-alpine

**Comment by alexsaab** [comment]
Hi, I also need support for this lib and php 8 

With best regards, Alex

**Comment by gmponos** [comment]
hi sorry for the delay
