### ISSUE TITLE
Suggestion to update documentation

### ISSUE THREAD

**Issue by slavo2** [gmponos/guzzle-log-middleware#7]
I have tried to use guzzle-log-middleware, roughly following the README,
however had problem with 

Uncaught PHP Exception LogicException: "No handler has been specified" 

When I have exchanged 

`$stack = new HandlerStack();`
with
`$stack = HandlerStack::create();`

(Thanks to https://stackoverflow.com/a/32684940 )

my problem was solved.

Suggestion: maybe you might want to update README similarly.

**Comment by gmponos** [comment]
Thank.. I made the changes.. please check. Let me know if something is not fine.
